name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v --package-path Landmarks/Landmarks
    - name: Run tests
      run: swift test -v --package-path Landmarks/Landmarks
